---
- name: Building Precheck Failures
  hosts: arista_switches        # group within the inventory to match on
  connection: network_cli       # required when connecting to switch devices
  become: yes
  become_method: enable
  gather_facts: no             # this defines ansible_facts
                                # (it runs *_facts on the target network switches)

  vars:
    ansible_ssh_pass: alta3

  tasks:

  - name: Vendor specific facts gathering
    eos_facts:
     gather_subset: all
    register: ansible_facts

  # dig into the data we want to reveal
  - name: Getting at network interfaces
    debug:
     var: ansible_facts

